# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ping_200_response

    Ping200Response(;
        status=nothing,
    )

    - status::String : Overall status of the TorchServe.
"""
Base.@kwdef mutable struct Ping200Response <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function Ping200Response(status, )
        OpenAPI.validate_property(Ping200Response, Symbol("status"), status)
        return new(status, )
    end
end # type Ping200Response

const _property_types_Ping200Response = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ Ping200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Ping200Response[name]))}

function check_required(o::Ping200Response)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Ping200Response }, name::Symbol, val)
end
